### PR TITLE
add ffmpegthumbnailer and keep main image feature

### PR DESCRIPTION
**Pull request by Mehrdad-Dadkhah**
Hi.
tanx for good package.

I add ffmpegthumbnailer as converter. in my test it is very fast and lightweight for generate thumbnail from video.
also change setters return to add chain call feature.
and add keep main image feature because we create thumbs and somebody may need them for other use.

### CODE REVIEW

**Comment by maetthu** [comment]
Thank you very much for your PR :smile: I will look at it in the next couple of days. From a quick glance over the code it looks good, one typo: convertor => converter.

**Comment by Mehrdad-Dadkhah** [comment]
WHOOOPs! excuse me for typo ... 
I fix it.

**Comment by maetthu** [comment]
np :) thx! Method names (get/setConvertor) are missing in 9109349 though.

**Comment by Mehrdad-Dadkhah** [comment]
tanx for checking
done!

**Comment by maetthu** [comment]
Thanks! will get back to you as soon.

**Comment by maetthu** [comment]
To keep backwards compatibility, I will change the default converter back to ffmpeg, but the rest is a great addition, thank you for your work :smile: I will add a few tests, do some cleanup (didn't work on it for quite some time) and release a new version soon.

**Comment by maetthu** [comment]
Some notes:
* I removed the keepMainImages flag, IMHO it's enough to set the output directory, the flag is redundant.
* Fixed the setConverter function: Whitelist wasn't being used and converter property not set

Rest will follow.

**Comment by Mehrdad-Dadkhah** [comment]
thank you very much.
tnx for add my name to read me.

**Pull request merged**
